title: ESMANN:IO
description: ESMANN:IO

url: https://esmann.io/
baseurl: ""
editurl: https://github.com/esmann-io/esmann-io.github.io/blob/master/
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index
  - title: Work
    url: /work
  - title: Blog
    url: /blog
  - title: TechTalk
    url: /techtalk
  - title: Contact
    url: /contact

social:
  github: martinesmann
  twitter: martinesmann
  facebook: martinesmann
  email: martin@esmann.io

google_analytics: "UA-72165567-1"
